DECLARE
	@PALABRA1 VARCHAR(20),
	@PALABRA2 VARCHAR(20),
	@SQL NVARCHAR(1000),
	@CONTADOR INT = 1,
	@LONGITUD INT,
	@COLUMNA VARCHAR(3);
	SET @PALABRA1 = 'JESUS';
	SET @PALABRA2 = 'jseus';
	
	SET @SQL = 'DROP TABLE IF EXISTS COMPARA'
	EXEC sp_sqlexec @SQL;

	SET @SQL = 'CREATE TABLE COMPARA (';

	SET @LONGITUD = LEN(@PALABRA1);

	WHILE @CONTADOR < @LONGITUD
	BEGIN
		SET @SQL = @SQL + SUBSTRING(@PALABRA1, @CONTADOR, 1) + CAST(@CONTADOR AS varchar(2)) + ' INT, '
		SET @CONTADOR = 1 + @CONTADOR;
	END
	SET @SQL = @SQL + SUBSTRING(@PALABRA1, @CONTADOR, 1) + CAST(@CONTADOR AS varchar(2)) + ' INT)'
	PRINT @SQL;
	EXEC sp_sqlexec @SQL;

	SET @LONGITUD = LEN(@PALABRA2);
	SET @CONTADOR = 1;

	WHILE @CONTADOR <= @LONGITUD
	BEGIN
		SET @COLUMNA = NULL;
		SET @SQL = 'INSERT INTO COMPARA (';
		SELECT TOP 1 @COLUMNA = COLUMN_NAME
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'COMPARA'
			AND LEFT(COLUMN_NAME, 1) = SUBSTRING(@PALABRA2, @CONTADOR, 1)
			AND ORDINAL_POSITION >= @CONTADOR;
		SET @SQL = @SQL + @COLUMNA + ') VALUES (' + CAST(1 AS CHAR(1)) + ')'
		IF @SQL IS NOT NULL
			PRINT @SQL
			EXEC sp_sqlexec @SQL;
		SET @CONTADOR = 1 + @CONTADOR;
	END

	SET @CONTADOR = 1;
	SET @SQL = 'SELECT';
	SET @LONGITUD = LEN(@PALABRA1);
	WHILE @CONTADOR < @LONGITUD
	BEGIN
		SET @SQL = @SQL + ' SUM(COALESCE(' + SUBSTRING(@PALABRA1, @CONTADOR, 1) + CAST(@CONTADOR AS CHAR(1)) + ', 0)) +'
		SET @CONTADOR = 1 + @CONTADOR;
	END
	SET @SQL = @SQL + ' SUM(COALESCE(' + SUBSTRING(@PALABRA1, @CONTADOR, 1) + CAST(@CONTADOR AS CHAR(1)) + ', 0)) AS TOT '
	SET @SQL = @SQL + 'FROM COMPARA';

	PRINT @SQL;

	EXEC sp_sqlexec @SQL;

	SELECT * FROM COMPARA
